platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!
install! 'cocoapods', :share_schemes_for_development_pods => ['SDWebImageYYPlugin']

target 'SDWebImageYYPlugin_Example' do
  pod 'SDWebImageYYPlugin', :path => '../'
  pod 'YYImage/WebP'

  target 'SDWebImageYYPlugin_Tests' do
    inherit! :search_paths
    pod 'Expecta'
    
  end
end
